ShopifyMetafieldEditor/Models/MetaFieldModel.cs
using System.ComponentModel.DataAnnotations;

namespace ShopifyMetaFieldEditor.Models
{
    public class MetaFieldModel
    {
        public long Id { get; set; }
        public long OwnerId { get; set; }

        [Required]
        [StringLength(16, MinimumLength = 3)]
        public string Namespace { get; set; }
        [Required]
        public string Key { get; set; }
        [Required]
        public string Value { get; set; }
    }
}

ShopifyMetafieldEditor/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShopifyMetaFieldEditor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ShopifyMetafieldEditor/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using ShopifySharp;

namespace ShopifyMetaFieldEditor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IShopifyFactory _shopifyFactory;

        public IndexModel(IShopifyFactory shopifyFactory)
        {
            _shopifyFactory = shopifyFactory;
        }

        public async Task OnGet()
        {
            var service = _shopifyFactory.CreateProductService();

            var products = await service.ListAsync();
            Products = products;
        }

        public IEnumerable<Product> Products { get; set; }
    }
}

ShopifyMetafieldEditor/Pages/Metafields.cshtml.cs
using System.Collections.Generic;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopifyMetaFieldEditor.Models;
using ShopifySharp;
using ShopifySharp.Filters;

namespace ShopifyMetaFieldEditor.Pages
{
    public class MetaFieldsModel : PageModel
    {
        private readonly IShopifyFactory _shopifyFactory;

        public MetaFieldsModel(IShopifyFactory shopifyFactory)
        {
            _shopifyFactory = shopifyFactory;
        }

        public async Task<ActionResult> OnGet(long productId)
        {
            var productService = _shopifyFactory.CreateProductService();
            var metafieldService = _shopifyFactory.CreateMetaFieldService();
            var product = await productService.GetAsync(productId,"title,id");
            Product = product;
            MetaFields =  await metafieldService.ListAsync(productId, "products", new MetaFieldFilter()
            {
                Namespace = "rls"
            });
            if (CreateModel == null)
            {
                CreateModel = new MetaFieldModel
                {
                    Key = "subtitle",
                    Namespace = "rls"
                };
            }

            return Page();
        }

        public async Task<ActionResult> OnPostUpdate(long productId, MetaFieldModel metaField)
        {
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                var metafieldService = _shopifyFactory.CreateMetaFieldService();
                var field = await metafieldService.UpdateAsync(metaField.Id, new MetaField()
                {
                    Namespace = metaField.Namespace,
                    Key = metaField.Key,
                    Value = metaField.Value
                });
                return RedirectToPage("Metafields", new {productId});
            }
            return await OnGet(productId);
        }

        public async Task<ActionResult> OnPostCreate(long productId)
        {
            if (ModelState.IsValid)
            {
                var metafieldService = _shopifyFactory.CreateMetaFieldService();
                await metafieldService.CreateAsync(new MetaField()
                {
                    Key = CreateModel.Key,
                    Namespace = CreateModel.Namespace,
                    Value = CreateModel.Value,
                    ValueType = "string",
                }, productId, "products");
                return RedirectToPage("Metafields", new {productId});
            }
            return await OnGet(productId);
        }

        public Product Product { get; set; }

        public IEnumerable<MetaField> MetaFields { get; set; }

        [BindProperty]
        public MetaFieldModel CreateModel { get; set; }
    }
}

ShopifyMetafieldEditor/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShopifyMetaFieldEditor.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ShopifyMetafieldEditor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<table>
   @foreach (var product in Model.Products)
   {
       <tr>
           <td><a asp-page="/Metafields" asp-route-productId="@product.Id">@product.Title</a></td>
       </tr>       
   }
</table>

ShopifyMetafieldEditor/Pages/Metafields.cshtml
@page
@model ShopifyMetaFieldEditor.Pages.MetaFieldsModel
@{
    ViewData["Title"] = "Metafields";
}

<h1>Metafields for @Model.Product.Title</h1>

@foreach (var metaField in Model.MetaFields)
{
    <form asp-page="/MetaFields" asp-route-productid="@Model.Product.Id" asp-page-handler="update" method="post">
        <input type="hidden" asp-for="@metaField.Id"/>
        <input type="hidden" asp-for="@metaField.OwnerId"/>
        <table>
            <tr>
                <td><input type="text" asp-for="@metaField.Namespace"/></td>
                <td><input type="text" asp-for="@metaField.Key"/></td>
                <td><input type="text" asp-for="@metaField.Value"/></td>
                <td><button type="submit">Update</button></td>
            </tr>
        </table>
    </form>
}

<form asp-page="/MetaFields" asp-route-productid="@Model.Product.Id" asp-page-handler="create" method="post">
    <table>
        <tr>
            <td><input type="text" asp-for="@Model.CreateModel.Namespace" /></td>
            <td><input type="text" asp-for="@Model.CreateModel.Key" /></td>
            <td><input type="text" asp-for="@Model.CreateModel.Value" /></td>
            <td><button type="submit">Create</button></td>
        </tr>
    </table>
</form>

ShopifyMetafieldEditor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopifyMetafieldEditor</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ShopifyMetafieldEditor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ShopifyMetafieldEditor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>